-- Registry2 Docker dev environment (issue #2116 spike).
--
-- The official mysql image's MYSQL_USER/MYSQL_DATABASE env vars only grant
-- that user privileges on the ONE database named at container creation
-- (elanregi_spice2, the dev DB) — not on the separate integration-test
-- schema (elanregi_dev_test_2, per .env.test.local) that
-- scripts/provision-schema.sh needs to DROP/CREATE from scratch.
--
-- Broadening the app-scoped user's grants to every elanregi_* schema (dev,
-- test, and any future one) avoids handing out root or a
-- separately-tracked root password that changes on every container
-- recreation (MYSQL_RANDOM_ROOT_PASSWORD).
--
-- KNOWN COUPLING: the username below (elanregi_spice) must match
-- docker-compose.yml's ${DB_USER} exactly. A .sql file here gets no
-- environment-variable substitution, so this can't read ${DB_USER}
-- directly — an attempted .sh-based version (using the entrypoint's
-- docker_process_sql helper for proper root auth under
-- MYSQL_RANDOM_ROOT_PASSWORD) hit inconsistent executable-bit handling on
-- Docker Desktop for Mac's bind mount and was reverted in favor of this
-- simpler, proven-reliable .sql file. If DB_USER in .env ever changes from
-- elanregi_spice, update the username below in the same change.
--
-- SYSTEM_VARIABLES_ADMIN: some tests need SET GLOBAL. E.g.
-- VerifyCarLandingPageTest::testOptoutMidTransactionFailureReturns500...
-- (tests/integration/VerifyCarLandingPageTest.php — not present in every
-- checkout/branch) runs `SET GLOBAL lock_wait_timeout = 1` to make a
-- deliberately-locked write fail fast instead of hanging for MySQL's
-- documented one-year default. Without this privilege the SET GLOBAL call
-- itself throws ("Access denied; you need ... SUPER or
-- SYSTEM_VARIABLES_ADMIN"), uncaught by the test, so it hangs to its outer
-- 10s curl timeout instead of failing fast with a clear error. MAMP's app
-- DB user apparently already has this (or SUPER) by default; the Docker
-- image starts every non-root user with neither.
--
-- Grant is global-scope only (not *.* ALL), since this is a
-- system-variable privilege, not a schema/table one — it grants no
-- schema/table access. It DOES unlock `SET GLOBAL
-- log_bin_trust_function_creators`, which several trigger-creating
-- migrations (e.g. database/migrations/20260905172137_convert_car_...
-- .php's enableTrustFunctionCreators()) attempt and currently
-- warn-and-continue on if it fails — with this grant, Docker now
-- succeeds at that call where an unprivileged prod user might not,
-- exercising a different code path locally than prod does. Harmless here
-- specifically because docker-compose.yml's `db` service already passes
-- `--disable-log-bin`, making the variable moot regardless of who can
-- set it.
--
-- Runs once, only against a fresh (empty) data directory — files in
-- /docker-entrypoint-initdb.d are ignored on a subsequent `docker compose
-- up` against an existing volume.
GRANT ALL PRIVILEGES ON `elanregi_%`.* TO 'elanregi_spice'@'%';
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO 'elanregi_spice'@'%';
FLUSH PRIVILEGES;
